language: python
python:
  - 2.7
services:
 - docker
install:
 - pip install -U pip wheel
 - pip install -r requirements.txt
 - pip list
before_script:
  - openssl version -a
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
script:
 - python -m pytest -x plugins/CryptMessage/Test
 - python -m pytest -x plugins/Bigfile/Test
 - python -m pytest -x plugins/AnnounceLocal/Test
 - python -m pytest -x plugins/OptionalManager/Test
 - python -m pytest src/Test --cov=src --cov-config src/Test/coverage.ini
before_install:
  - pip install -U pytest mock pytest-cov selenium
  - pip install codecov
  - pip install coveralls
  - docker build -t zeronet .
  - docker run -d -v $PWD:/root/data -p 15441:15441 -p 127.0.0.1:43110:43110 zeronet
after_success:
  - codecov
  - coveralls --rcfile=src/Test/coverage.ini
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    recipients:
      hello@zeronet.io
    on_success: change
